version: '3'

services:
  djangoProject1_postgresql:
    image: postgres:12
    container_name: djangoProject1_postgresql
    volumes:
      - djangoProject1_postgresql:/ver/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - djangoProject1_network

volumes:
  djangoProject1_postgresql:
    external: true

networks:
  djangoProject1_network:
    external: true
